# Generated by Django 5.1.5 on 2025-01-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=200)),
                ('isdone', models.BooleanField(default=False)),
                ('date', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
